### ISSUE TITLE
Error message when using --delete flag

### ISSUE THREAD

**Issue by swindt** [krzysztof-nowakowski/datts#1]
Hi,
I was getting the following error message when using the --delete flag:
`imaplib.error: UID command error: BAD ['Error in IMAP command UID STORE: Flags list contains non-atoms (0.001 + 0.000 secs).']
`
To fix it, just put the "\\Deleted" into brackets: 
` server.uid('store', mail_id, '+FLAGS', '(\\Deleted)')`
instead of
` server.uid('store', mail_id, '+FLAGS', '\\Deleted')`

**Comment by krzysztof-nowakowski** [comment]
hi, can you tell me from what server have you tried to download and received this error?

**Comment by swindt** [comment]
Hi, actually, I don't know, what type of mailserver is used. I am using a server from my hosted website provided by hetzner.de. Server is mail.your-server.de. Maybe this helps for clarification.

**Comment by krzysztof-nowakowski** [comment]
I have added ('\\Deleted') flag to the code. After tests, it is working. Looks like this flag should be embedded between parentheses: https://tools.ietf.org/html/rfc3501.html#section-6.4.6

Thanks for reporting this, I will close this bug now.
